/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QLKHView;
import QLKHController.*;
import javax.swing.JFrame;
/**
 *
 * @author trinh
 */
public class indexFormQL extends javax.swing.JFrame {

    /**
     * Creates new form indexForm
     */
    public static JFrame temp = null;
    
    public indexFormQL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lblKho = new javax.swing.JLabel();
        lblQuanLy = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDangXuat = new QLKHView.swing.Button();
        btnCuaHang1 = new QLKHView.swing.Button();
        btnSanPham1 = new QLKHView.swing.Button();
        btnNhaCungCap1 = new QLKHView.swing.Button();
        btnNguoiDung = new QLKHView.swing.Button();
        btnDay1 = new QLKHView.swing.Button();
        btnPhieuNhap = new QLKHView.swing.Button();
        btnPhieuXuat = new QLKHView.swing.Button();
        jLabel3 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblKho.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblKho.setText("QUẢN LÝ KHO XE ĐẠP");
        jPanel1.add(lblKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, 69));

        lblQuanLy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuanLy.setText("QUẢN LÝ");
        jPanel1.add(lblQuanLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 50, 90, -1));

        btnCuaHang1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnCuaHang1.setText("Quản lý cửa hàng");
        btnCuaHang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuaHang1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCuaHang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, 234, 47));

        btnSanPham1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnSanPham1.setText("Quản lý sản phẩm");
        btnSanPham1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPham1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSanPham1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 234, 47));

        btnNhaCungCap1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnNhaCungCap1.setText("Quản lý nhà cung cấp");
        btnNhaCungCap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaCungCap1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnNhaCungCap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 234, 47));

        btnNguoiDung.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnNguoiDung.setText("Quản lý người dùng");
        btnNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguoiDungActionPerformed(evt);
            }
        });
        jPanel1.add(btnNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 234, 47));

        btnDay1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnDay1.setText("Quản lý dãy");
        btnDay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDay1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 234, 47));

        btnPhieuNhap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnPhieuNhap.setText("Quản lý phiếu nhập");
        btnPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuNhapActionPerformed(evt);
            }
        });
        jPanel1.add(btnPhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 234, 47));

        btnPhieuXuat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btnPhieuXuat.setText("Quản lý phiếu xuất");
        btnPhieuXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuXuatActionPerformed(evt);
            }
        });
        jPanel1.add(btnPhieuXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 350, 234, 47));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLKHView/image/milad-fakurian-vON-QEM5Ako-unsplash.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        NguoiDungController.loginPage();
        this.dispose();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnCuaHang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuaHang1ActionPerformed
        // TODO add your handling code here:
        CuaHangController.QLCuaHangPage();
        this.setVisible(false);
        temp = this;
    }//GEN-LAST:event_btnCuaHang1ActionPerformed

    private void btnSanPham1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPham1ActionPerformed
        // TODO add your handling code here:
        SanPhamController.QLSanPhamPage();
        this.setVisible(false);
        temp = this;
    }//GEN-LAST:event_btnSanPham1ActionPerformed

    private void btnNhaCungCap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaCungCap1ActionPerformed
        // TODO add your handling code here:
        NhaCungCapController.QLNhaCungCapPage();
        this.setVisible(false);
        temp = this;
    }//GEN-LAST:event_btnNhaCungCap1ActionPerformed

    private void btnNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguoiDungActionPerformed
        // TODO add your handling code here:
        NguoiDungController.QLNguoiDungpage();
        this.setVisible(false);
        temp = this;
    }//GEN-LAST:event_btnNguoiDungActionPerformed

    private void btnDay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDay1ActionPerformed
        // TODO add your handling code here:
        DayController.QLDayPage();
        this.setVisible(false);
        temp = this;
    }//GEN-LAST:event_btnDay1ActionPerformed

    private void btnPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuNhapActionPerformed
        // TODO add your handling code here:
         PhieuNhapController.QLPhieuNhapPage();
        this.setVisible(false);
        temp = this;
    }//GEN-LAST:event_btnPhieuNhapActionPerformed

    private void btnPhieuXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuXuatActionPerformed
        // TODO add your handling code here:
         PhieuXuatController.QLPhieuXuatPage();
        this.setVisible(false);
        temp = this;
    }//GEN-LAST:event_btnPhieuXuatActionPerformed

    /**
     */
    public static void runIndexQL() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(indexFormQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(indexFormQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(indexFormQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(indexFormQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new indexFormQL().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private QLKHView.swing.Button btnCuaHang1;
    private QLKHView.swing.Button btnDangXuat;
    private QLKHView.swing.Button btnDay1;
    private QLKHView.swing.Button btnNguoiDung;
    private QLKHView.swing.Button btnNhaCungCap1;
    private QLKHView.swing.Button btnPhieuNhap;
    private QLKHView.swing.Button btnPhieuXuat;
    private QLKHView.swing.Button btnSanPham1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKho;
    private javax.swing.JLabel lblQuanLy;
    // End of variables declaration//GEN-END:variables
}
