/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QLKHView;

import QLKHModel.*;
import QLKHController.*;
import static QLKHView.indexFormQL.temp;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author VTTDung
 */
public class QLCuaHangForm extends javax.swing.JFrame {

    /**
     * Creates new form QLCuaHangForm
     */
   public static boolean check;
    final static String header[] = {"Mã cửa hàng","Tên cửa hàng","Số điện thoại","Địa chỉ"};
    final static DefaultTableModel tb = new DefaultTableModel(header, 0);
    public QLCuaHangForm() {
        initComponents();
        loadTableCuaHang(CuaHangController.listCuaHang(""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCuaHang = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCuaHang = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        txtMaCuaHang = new QLKHView.swing.TextField();
        txtTenCuaHang = new QLKHView.swing.TextField();
        txtSoDienThoai = new QLKHView.swing.TextField();
        txtDiaChi = new QLKHView.swing.TextField();
        btnQuayLai = new QLKHView.swing.Button();
        btnXoa = new QLKHView.swing.Button();
        btnLamMoi = new QLKHView.swing.Button();
        btnTim = new QLKHView.swing.Button();
        btnThem = new QLKHView.swing.Button();
        btnSua = new QLKHView.swing.Button();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCuaHang.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblCuaHang.setText("QUẢN LÝ CỬA HÀNG");
        jPanel1.add(lblCuaHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        tbCuaHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã cửa hàng", "Tên cửa hàng", "Số điện thoại", "Địa chỉ"
            }
        ));
        tbCuaHang.setToolTipText("");
        tbCuaHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbCuaHang.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tbCuaHang.setVerifyInputWhenFocusTarget(false);
        tbCuaHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCuaHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbCuaHang);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 1200, 220));

        txtMaCuaHang.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMaCuaHang.setLabelText("Mã cửa hàng");
        txtMaCuaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaCuaHangActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaCuaHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 230, -1));

        txtTenCuaHang.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTenCuaHang.setLabelText("Tên cửa hàng");
        jPanel1.add(txtTenCuaHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 230, -1));

        txtSoDienThoai.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSoDienThoai.setLabelText("Số điện thoại");
        jPanel1.add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 230, -1));

        txtDiaChi.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDiaChi.setLabelText("Địa chỉ");
        jPanel1.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 230, -1));

        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/return.png"))); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuayLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 30, 80, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 80, -1));

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        jPanel1.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 330, 80, -1));

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/find.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        jPanel1.add(btnTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 80, -1));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 80, -1));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLKHView/image/milad-fakurian-wxvYVpjWxg4-unsplash.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1200, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1201, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   public static void loadTableCuaHang(ArrayList<CuaHangModel> lch){
        tb.getDataVector().removeAllElements();
        for(int i=0; i < lch.size(); i++){
            String[] ch = {lch.get(i).getMaCH(), lch.get(i).getTenCH(), lch.get(i).getSdtCH(), lch.get(i).getDiaChiCH()};
            tb.addRow(ch);
            tbCuaHang.setModel(tb);
        }
    }    public static CuaHangModel getCuaHangInput(){
       CuaHangModel ch = new CuaHangModel();
       ch.setMaCH(txtMaCuaHang.getText());
       ch.setTenCH(txtTenCuaHang.getText());
       ch.setDiaChiCH(txtDiaChi.getText());
       ch.setSdtCH(txtSoDienThoai.getText());
       return ch;
    }
    
    public void showMessage(String msg, boolean checkMsg){
        if(checkMsg){
            JOptionPane.showMessageDialog(this, msg,"Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else JOptionPane.showMessageDialog(this, msg,"Thông báo", JOptionPane.ERROR_MESSAGE);
    }    public static boolean xacNhanXoa(){
        int input = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        return input == JOptionPane.YES_OPTION;
    }
    private void tbCuaHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCuaHangMouseClicked
        // TODO add your handling code here:
        boolean checkClick = tbCuaHang.isEditing();
        if (checkClick == false){
            JTable target = (JTable) evt.getSource();
            int rowIndex = target.getSelectedRow();
            int col = 0;
            txtMaCuaHang.setText((String)tbCuaHang.getValueAt(rowIndex,col));
            txtTenCuaHang.setText((String)tbCuaHang.getValueAt(rowIndex,col+1));
            txtSoDienThoai.setText((String)tbCuaHang.getValueAt(rowIndex,col+2));
            txtDiaChi.setText((String)tbCuaHang.getValueAt(rowIndex,col+3));
            txtMaCuaHang.setEnabled(false);
            check = true;
        }   
    }//GEN-LAST:event_tbCuaHangMouseClicked

    private void txtMaCuaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaCuaHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaCuaHangActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        if(temp != null){
          temp.setVisible(true);
          temp = null;  
        }
        else indexFormNVTN.runIndexNVTN();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        new CuaHangController(this).doDeleteCuaHang();
        btnLamMoiActionPerformed(evt);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        txtMaCuaHang.setEnabled(true);
        check = false;
        txtDiaChi.setText("");
        txtMaCuaHang.setText("");
        txtSoDienThoai.setText("");
        txtTenCuaHang.setText("");
        tb.getDataVector().removeAllElements();
        loadTableCuaHang(CuaHangController.listCuaHang(""));
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        new CuaHangController(this).doSearchCuaHang();
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        new CuaHangController(this).doAddCuaHang();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        new CuaHangController(this).doUpdateCuaHang();
    }//GEN-LAST:event_btnSuaActionPerformed

    /**
     */
    public static void runQLCuaHang() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLCuaHangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLCuaHangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLCuaHangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLCuaHangForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QLCuaHangForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private QLKHView.swing.Button btnLamMoi;
    private QLKHView.swing.Button btnQuayLai;
    private QLKHView.swing.Button btnSua;
    private QLKHView.swing.Button btnThem;
    private QLKHView.swing.Button btnTim;
    private QLKHView.swing.Button btnXoa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCuaHang;
    private static javax.swing.JTable tbCuaHang;
    private static QLKHView.swing.TextField txtDiaChi;
    private static QLKHView.swing.TextField txtMaCuaHang;
    private static QLKHView.swing.TextField txtSoDienThoai;
    private static QLKHView.swing.TextField txtTenCuaHang;
    // End of variables declaration//GEN-END:variables
}
