/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QLKHView;

import QLKHController.DayController;
import QLKHModel.DayModel;
import QLKHModel.SanPhamModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trinh
 */
public class QLDay_ChiTietForm extends javax.swing.JFrame {

    /**
     * Creates new form QLDay_ChiTietForm
     */
    public static boolean check;
    final static String header[] = {"Mã sản phẩm","Số lượng","Ghi chú"};
    final static DefaultTableModel tb = new DefaultTableModel(header, 0);
    public QLDay_ChiTietForm(String MaDay) {
        initComponents();
        DayModel d = DayController.listChiTietDay(MaDay,"","");
        txtMaDay.setText(MaDay);
        txtMaDay.setEnabled(false);
        loadTableChiTietDay(d.getDanhSachSP()); 
    }

    public static void loadTableChiTietDay(ArrayList<SanPhamModel> ctd){
        tb.getDataVector().removeAllElements();
        for(int i=0; i < ctd.size(); i++){
            String[] d = {ctd.get(i).getMaSP(), Integer.toString(ctd.get(i).getSoLuong()), ctd.get(i).getGhiChu()};
            tb.addRow(d);
            tbChiTietDay.setModel(tb);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCuaHang = new javax.swing.JLabel();
        txtMaDay = new javax.swing.JTextField();
        txtMaSanPham = new QLKHView.swing.TextField();
        txtGhiChu = new QLKHView.swing.TextField();
        spnSoLuong = new QLKHView.swing.Spinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbChiTietDay = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        btnDong = new QLKHView.swing.Button();
        btnThem1 = new QLKHView.swing.Button();
        btnTim1 = new QLKHView.swing.Button();
        btnSua1 = new QLKHView.swing.Button();
        btnXoa1 = new QLKHView.swing.Button();
        btnLamMoi1 = new QLKHView.swing.Button();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCuaHang.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblCuaHang.setText("CHI TIẾT DÃY");
        jPanel1.add(lblCuaHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        txtMaDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDayActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 90, -1));

        txtMaSanPham.setLabelText("Mã sản phẩm");
        jPanel1.add(txtMaSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 207, 211, -1));

        txtGhiChu.setLabelText("Ghi chú");
        jPanel1.add(txtGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(849, 207, 211, -1));

        spnSoLuong.setLabelText("Số lượng");
        jPanel1.add(spnSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 206, 211, -1));

        tbChiTietDay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Sản phẩm", "Số lượng", "Ghi chú"
            }
        ));
        tbChiTietDay.setPreferredSize(new java.awt.Dimension(300, 80));
        tbChiTietDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbChiTietDayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbChiTietDay);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 1200, 210));

        btnDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/close.png"))); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });
        jPanel1.add(btnDong, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 50, 80, -1));

        btnThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus.png"))); // NOI18N
        btnThem1.setText("Thêm");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 80, -1));

        btnTim1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/find.png"))); // NOI18N
        btnTim1.setText("Tìm");
        btnTim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnTim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 80, -1));

        btnSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        btnSua1.setText("Sửa");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 80, -1));

        btnXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear.png"))); // NOI18N
        btnXoa1.setText("Xóa");
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 80, -1));

        btnLamMoi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        btnLamMoi1.setText("Làm mới");
        btnLamMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoi1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLamMoi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 340, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLKHView/image/milad-fakurian-wxvYVpjWxg4-unsplash.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 1200, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoi1ActionPerformed
        // TODO add your handling code here:
        txtMaSanPham.setEnabled(true);
        check = false;
        tb.getDataVector().removeAllElements();
        loadTableChiTietDay(DayController.listChiTietDay(txtMaDay.getText(),"","").getDanhSachSP());
        txtMaSanPham.setText("");
        spnSoLuong.setValue(0);
        txtGhiChu.setText("");
    }//GEN-LAST:event_btnLamMoi1ActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        // TODO add your handling code here:
        new DayController(this).doDeleteChiTietDay(txtMaDay.getText());
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        // TODO add your handling code here:
        new DayController(this).doUpdateChiTietDay(txtMaDay.getText());
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void btnTim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTim1ActionPerformed
        // TODO add your handling code here:
        new DayController(this).doSearchChiTietDay(txtMaDay.getText());
    }//GEN-LAST:event_btnTim1ActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        // TODO add your handling code here:
        new DayController(this).doAddChiTietDay(txtMaDay.getText());
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    private void tbChiTietDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbChiTietDayMouseClicked
        // TODO add your handling code here:
        boolean checkClick = tbChiTietDay.isEditing();
        if (checkClick == false){
            JTable target = (JTable) evt.getSource();
            int rowIndex = target.getSelectedRow();
            txtMaSanPham.setText((String)tbChiTietDay.getValueAt(rowIndex,0));
            spnSoLuong.setValue(Integer.valueOf((String)tbChiTietDay.getValueAt(rowIndex,1)));
            txtGhiChu.setText((String)tbChiTietDay.getValueAt(rowIndex,2));
            txtMaSanPham.setEnabled(false);
            check = true;
        }
    }//GEN-LAST:event_tbChiTietDayMouseClicked

    private void txtMaDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDayActionPerformed

    public static SanPhamModel getChiTietDayInput(){
       SanPhamModel sp = new SanPhamModel();
       sp.setMaSP(txtMaSanPham.getText());
       sp.setSoLuong((int)spnSoLuong.getValue());
       sp.setGhiChu(txtGhiChu.getText());
       return sp;
    }
    
    public static boolean xacNhanXoa(){
        int input = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        return input == JOptionPane.YES_OPTION;
    }
    
    public void showMessage(String msg, boolean checkMsg){
        if(checkMsg){
            JOptionPane.showMessageDialog(this, msg,"Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else JOptionPane.showMessageDialog(this, msg,"Thông báo", JOptionPane.ERROR_MESSAGE);
    }
    /**
     * @param MaDay
     */
    public static void runViewDetailD(String MaDay) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDay_ChiTietForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDay_ChiTietForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDay_ChiTietForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDay_ChiTietForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QLDay_ChiTietForm(MaDay).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private QLKHView.swing.Button btnDong;
    private QLKHView.swing.Button btnLamMoi1;
    private QLKHView.swing.Button btnSua1;
    private QLKHView.swing.Button btnThem1;
    private QLKHView.swing.Button btnTim1;
    private QLKHView.swing.Button btnXoa1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCuaHang;
    protected static QLKHView.swing.Spinner spnSoLuong;
    protected static javax.swing.JTable tbChiTietDay;
    protected static QLKHView.swing.TextField txtGhiChu;
    private javax.swing.JTextField txtMaDay;
    protected static QLKHView.swing.TextField txtMaSanPham;
    // End of variables declaration//GEN-END:variables
}
