/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QLKHView;
import QLKHModel.*;
import QLKHController.*;
import static QLKHView.indexFormQL.temp;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;  
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author VTTDung
 */
public class QLNguoiDungForm extends javax.swing.JFrame {
    /**
     * Creates new form QLNguoiDungForm
     */
    public static boolean check;
    //public static boolean checkSearch = false;
    final static String header[] = {"Mã người dùng","Chức vụ","Mật khẩu","Tên người dùng","Số điện thoại","Địa chỉ","Ngày sinh","Giới tính","Căn cước"};
    final static DefaultTableModel tb = new DefaultTableModel(header, 0);
    public QLNguoiDungForm() {
        initComponents();
        loadTableNguoiDung(NguoiDungController.listNguoiDung(""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNguoiDung = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNguoiDung = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        txtTenNguoiDung = new QLKHView.swing.TextField();
        txtMaNguoiDung = new QLKHView.swing.TextField();
        cboChucVu = new QLKHView.swing.Combobox();
        txtDiaChi = new QLKHView.swing.TextField();
        txtCanCuoc = new QLKHView.swing.TextField();
        txtMatKhau = new QLKHView.swing.TextField();
        cboGioiTinh = new QLKHView.swing.Combobox();
        txtNgaySinh = new QLKHView.swing.TextField();
        txtSoDienThoai = new QLKHView.swing.TextField();
        btnQuayLai = new QLKHView.swing.Button();
        btnThem = new QLKHView.swing.Button();
        btnTim = new QLKHView.swing.Button();
        btnSua = new QLKHView.swing.Button();
        btnXoa = new QLKHView.swing.Button();
        btnLamMoi = new QLKHView.swing.Button();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNguoiDung.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblNguoiDung.setText("QUẢN LÝ NGƯỜI DÙNG");
        jPanel1.add(lblNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 35, -1, -1));

        tbNguoiDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã người dùng", "Chức vụ", "Mật khẩu", "Tên người dùng", "SĐT", "Địa chỉ", "Ngày sinh", "Giới tính", "Căn cước"
            }
        ));
        tbNguoiDung.setToolTipText("");
        tbNguoiDung.setGridColor(new java.awt.Color(255, 255, 255));
        tbNguoiDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNguoiDungMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbNguoiDung);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 447, 1210, 160));

        txtTenNguoiDung.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTenNguoiDung.setLabelText("Tên người dùng");
        jPanel1.add(txtTenNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 241, 60));

        txtMaNguoiDung.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMaNguoiDung.setLabelText("Mã người dùng");
        txtMaNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNguoiDungActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 143, 241, 60));

        cboChucVu.setMaximumRowCount(10);
        cboChucVu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*", "Quan ly", "Nhan vien tiep nhan", "Nhan vien kiem ke" }));
        cboChucVu.setLabeText("Chức vụ");
        cboChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboChucVuActionPerformed(evt);
            }
        });
        jPanel1.add(cboChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 241, 60));

        txtDiaChi.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDiaChi.setLabelText("Địa chỉ");
        jPanel1.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 220, 240, 60));

        txtCanCuoc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCanCuoc.setLabelText("Căn cước");
        jPanel1.add(txtCanCuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 307, 241, 60));

        txtMatKhau.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMatKhau.setLabelText("Mật khẩu");
        jPanel1.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 300, 240, 60));

        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*", "Nam", "Nữ" }));
        cboGioiTinh.setLabeText("Giới tính");
        jPanel1.add(cboGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 240, 60));

        txtNgaySinh.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNgaySinh.setLabelText("Ngày sinh");
        jPanel1.add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 241, 60));

        txtSoDienThoai.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSoDienThoai.setLabelText("Số điện thoại");
        jPanel1.add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 241, 60));

        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/return.png"))); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuayLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 70, 80, -1));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 80, -1));

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/find.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        jPanel1.add(btnTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 80, -1));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 80, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 80, -1));

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        jPanel1.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 400, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLKHView/image/milad-fakurian-wxvYVpjWxg4-unsplash.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 1200, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbNguoiDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNguoiDungMouseClicked
        // TODO add your handling code here:
        boolean checkClick = tbNguoiDung.isEditing();
        if (checkClick == false){
            JTable target = (JTable) evt.getSource();
            int rowIndex = target.getSelectedRow();
            int col = 0;
            txtMaNguoiDung.setText((String)tbNguoiDung.getValueAt(rowIndex,col));
            cboChucVu.setSelectedItem((String)tbNguoiDung.getValueAt(rowIndex,col+1));
            txtMatKhau.setText((String)tbNguoiDung.getValueAt(rowIndex,col+2));
            txtTenNguoiDung.setText((String)tbNguoiDung.getValueAt(rowIndex,col+3));
            txtSoDienThoai.setText((String)tbNguoiDung.getValueAt(rowIndex,col+4));
            txtDiaChi.setText((String)tbNguoiDung.getValueAt(rowIndex,col+5));
            txtNgaySinh.setText((String)tbNguoiDung.getValueAt(rowIndex,col+6));
            cboGioiTinh.setSelectedItem((String)tbNguoiDung.getValueAt(rowIndex,col+7));
            txtCanCuoc.setText((String)tbNguoiDung.getValueAt(rowIndex,col+8));
            txtMaNguoiDung.setEnabled(false);
            check = true;
        }       
    }//GEN-LAST:event_tbNguoiDungMouseClicked

    private void cboChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboChucVuActionPerformed

    private void txtMaNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNguoiDungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNguoiDungActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        temp.setVisible(true);
        temp = null;
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        new NguoiDungController(this).doAddNguoiDung();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        new NguoiDungController(this).doSearchNguoiDung();
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        new NguoiDungController(this).doUpdateNguoiDung();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        new NguoiDungController(this).doDeleteNguoiDung();
        btnLamMoiActionPerformed(evt);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
       txtMaNguoiDung.setEnabled(true);
        check = false;
        txtCanCuoc.setText("");
        txtDiaChi.setText("");
        txtMaNguoiDung.setText("");
        txtMatKhau.setText("");
        txtNgaySinh.setText("");
        txtSoDienThoai.setText("");
        txtTenNguoiDung.setText("");
        cboChucVu.setSelectedIndex(0);
        cboGioiTinh.setSelectedIndex(0);
        tb.getDataVector().removeAllElements();
        loadTableNguoiDung(NguoiDungController.listNguoiDung(""));
    }//GEN-LAST:event_btnLamMoiActionPerformed
    public static void loadTableNguoiDung(ArrayList<NguoiDungModel> lnd){
        //ArrayList<NguoiDungModel> lnd;
        tb.getDataVector().removeAllElements();
        for(int i=0; i < lnd.size(); i++){
            String[] nd = {lnd.get(i).getMaND(), lnd.get(i).getChucVu(), lnd.get(i).getMatKhau(), lnd.get(i).getTenND(), lnd.get(i).getSdtND(), lnd.get(i).getDiaChiND(), lnd.get(i).getNgaySinh(), lnd.get(i).getGioiTinh(), lnd.get(i).getCanCuoc()};
            tb.addRow(nd);
            tbNguoiDung.setModel(tb);
        }
    }

        public static NguoiDungModel getNguoiDungInput(){
       NguoiDungModel nd = new NguoiDungModel();
       nd.setMaND(txtMaNguoiDung.getText());
       nd.setTenND(txtTenNguoiDung.getText());
       nd.setDiaChiND(txtDiaChi.getText());
       nd.setGioiTinh(cboGioiTinh.getSelectedItem().toString());
       nd.setChucVu(cboChucVu.getSelectedItem().toString());
       nd.setSdtND(txtSoDienThoai.getText());
       nd.setNgaySinh(txtNgaySinh.getText());
       nd.setMatKhau(txtMatKhau.getText());
       nd.setCanCuoc(txtCanCuoc.getText());
       return nd;
    }
    
    public void showMessage(String msg, boolean checkMsg){
        if(checkMsg){
            JOptionPane.showMessageDialog(this, msg,"Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else JOptionPane.showMessageDialog(this, msg,"Thông báo", JOptionPane.ERROR_MESSAGE);
    }
        
    public static boolean xacNhanXoa(){
        int input = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        return input == JOptionPane.YES_OPTION;
    }
    
    /**
     */
    public static void runQLNguoiDung() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNguoiDungForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNguoiDungForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNguoiDungForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNguoiDungForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QLNguoiDungForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private QLKHView.swing.Button btnLamMoi;
    private QLKHView.swing.Button btnQuayLai;
    private QLKHView.swing.Button btnSua;
    private QLKHView.swing.Button btnThem;
    private QLKHView.swing.Button btnTim;
    private QLKHView.swing.Button btnXoa;
    protected static QLKHView.swing.Combobox cboChucVu;
    protected static QLKHView.swing.Combobox cboGioiTinh;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNguoiDung;
    protected static javax.swing.JTable tbNguoiDung;
    protected static QLKHView.swing.TextField txtCanCuoc;
    protected static QLKHView.swing.TextField txtDiaChi;
    protected static QLKHView.swing.TextField txtMaNguoiDung;
    protected static QLKHView.swing.TextField txtMatKhau;
    protected static QLKHView.swing.TextField txtNgaySinh;
    protected static QLKHView.swing.TextField txtSoDienThoai;
    protected static QLKHView.swing.TextField txtTenNguoiDung;
    // End of variables declaration//GEN-END:variables
}
