/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QLKHView;
import QLKHModel.*;
import QLKHController.*;
import static QLKHView.indexFormQL.temp;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author VTTDung
 */
public class QLNhaCungCapForm extends javax.swing.JFrame {

    /**
     * Creates new form QLNhaCungCapForm
     */
    public static boolean check;
    final static String header[] ={"Mã nhà cung cấp","Tên nhà cung cấp","Số điện thoại","Địa chỉ"};
    final static DefaultTableModel tb = new DefaultTableModel(header, 0);
    public QLNhaCungCapForm() {
        initComponents();
        loadTableNhaCungCap(NhaCungCapController.listNhaCungCap(""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPannel = new javax.swing.JPanel();
        lblNhaCungCap = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbNhaCungCap = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        txtMaNhaCungCap = new QLKHView.swing.TextField();
        txtTenNhaCungCap = new QLKHView.swing.TextField();
        txtSoDienThoai = new QLKHView.swing.TextField();
        txtDiaChi = new QLKHView.swing.TextField();
        btnQuayLai = new QLKHView.swing.Button();
        btnThem = new QLKHView.swing.Button();
        btnTim = new QLKHView.swing.Button();
        btnSua = new QLKHView.swing.Button();
        btnXoa = new QLKHView.swing.Button();
        btnLamMoi = new QLKHView.swing.Button();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPannel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JPannel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNhaCungCap.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblNhaCungCap.setText("QUẢN LÝ NHÀ CUNG CẤP");
        JPannel.add(lblNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 48, -1, -1));

        tbNhaCungCap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã nhà cung cấp", "Tên nhà cung cấp", "Số điện thoại", "Địa chỉ"
            }
        ));
        tbNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhaCungCapMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbNhaCungCap);

        JPannel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 1200, 160));

        txtMaNhaCungCap.setLabelText("Mã nhà cung cấp");
        JPannel.add(txtMaNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 159, 230, -1));

        txtTenNhaCungCap.setLabelText("Tên nhà cung cấp");
        JPannel.add(txtTenNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 263, 230, -1));

        txtSoDienThoai.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtSoDienThoai.setLabelText("Số điện thoại");
        JPannel.add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 162, 229, -1));

        txtDiaChi.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDiaChi.setLabelText("Địa chỉ");
        JPannel.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 255, 230, -1));

        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/return.png"))); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });
        JPannel.add(btnQuayLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 50, 80, -1));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        JPannel.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 80, -1));

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/find.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        JPannel.add(btnTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 80, -1));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        JPannel.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 80, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        JPannel.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 80, -1));

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        JPannel.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 370, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLKHView/image/milad-fakurian-wxvYVpjWxg4-unsplash.jpg"))); // NOI18N
        JPannel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static void loadTableNhaCungCap(ArrayList<NhaCungCapModel> lncc){
        tb.getDataVector().removeAllElements();
        for(int i=0; i < lncc.size(); i++){
            String[] ncc = {lncc.get(i).getMaNCC(), lncc.get(i).getTenNCC(), lncc.get(i).getSdtNCC(), lncc.get(i).getDiaChiNCC()};
            tb.addRow(ncc);
            tbNhaCungCap.setModel(tb);
        }
    }     public static NhaCungCapModel getNhaCungCapInput(){
       NhaCungCapModel ncc = new NhaCungCapModel();
       ncc.setMaNCC(txtMaNhaCungCap.getText());
       ncc.setTenNCC(txtTenNhaCungCap.getText());
       ncc.setDiaChiNCC(txtDiaChi.getText());
       ncc.setSdtNCC(txtSoDienThoai.getText());
       return ncc;
    }
    
    public void showMessage(String msg, boolean checkMsg){
        if(checkMsg){
            JOptionPane.showMessageDialog(this, msg,"Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else JOptionPane.showMessageDialog(this, msg,"Thông báo", JOptionPane.ERROR_MESSAGE);
    }    public static boolean xacNhanXoa(){
        int input = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        return input == JOptionPane.YES_OPTION;
    }
    private void tbNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhaCungCapMouseClicked
        // TODO add your handling code here:
         boolean checkClick = tbNhaCungCap.isEditing();
         if (checkClick == false){
            JTable target = (JTable) evt.getSource();
            int rowIndex = target.getSelectedRow();
            int col = 0;
            txtMaNhaCungCap.setText((String)tbNhaCungCap.getValueAt(rowIndex,col));
            txtTenNhaCungCap.setText((String)tbNhaCungCap.getValueAt(rowIndex,col+1));
            txtSoDienThoai.setText((String)tbNhaCungCap.getValueAt(rowIndex,col+2));
            txtDiaChi.setText((String)tbNhaCungCap.getValueAt(rowIndex,col+3));
            txtMaNhaCungCap.setEnabled(false);
            check = true;
        }  
    }//GEN-LAST:event_tbNhaCungCapMouseClicked

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        this.dispose();
        if(temp != null){
          temp.setVisible(true);
          temp = null;  
        }
        else indexFormNVTN.runIndexNVTN();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        new NhaCungCapController(this).doAddNhaCungCap();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        new NhaCungCapController(this).doSearchNhaCungCap();
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        new NhaCungCapController(this).doUpdateNhaCungCap();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        new NhaCungCapController(this).doDeleteNhaCungCap();
        btnLamMoiActionPerformed(evt);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        txtMaNhaCungCap.setEnabled(true);
        check = false;
        txtDiaChi.setText("");
        txtMaNhaCungCap.setText("");
        txtSoDienThoai.setText("");
        txtTenNhaCungCap.setText("");
        tb.getDataVector().removeAllElements();
        loadTableNhaCungCap(NhaCungCapController.listNhaCungCap(""));
    }//GEN-LAST:event_btnLamMoiActionPerformed

    /**
     */
    public static void runQLNhaCungCap() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNhaCungCapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNhaCungCapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNhaCungCapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNhaCungCapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(() -> {
            new QLNhaCungCapForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JPanel JPannel;
    private QLKHView.swing.Button btnLamMoi;
    private QLKHView.swing.Button btnQuayLai;
    private QLKHView.swing.Button btnSua;
    private QLKHView.swing.Button btnThem;
    private QLKHView.swing.Button btnTim;
    private QLKHView.swing.Button btnXoa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNhaCungCap;
    protected static javax.swing.JTable tbNhaCungCap;
    protected static QLKHView.swing.TextField txtDiaChi;
    protected static QLKHView.swing.TextField txtMaNhaCungCap;
    protected static QLKHView.swing.TextField txtSoDienThoai;
    protected static QLKHView.swing.TextField txtTenNhaCungCap;
    // End of variables declaration//GEN-END:variables
}
