/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QLKHView;
import QLKHModel.*;
import QLKHController.*;
import static QLKHView.indexFormQL.temp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author VTTDung
 */
public class QLPhieuXuatForm extends javax.swing.JFrame {

    /**
     * Creates new form QLPhieuXuatForm
     */
    public static boolean check;
    final static String header[] = {"Mã phiếu xuất","Ngày tạo","Mã cửa hàng","Người tạo","Trạng thái","Ngày xuất"};
    final static DefaultTableModel tb = new DefaultTableModel(header, 0);
    public QLPhieuXuatForm() {
        initComponents();
        txtNgayTao.setEnabled(false);
        txtNgayXuat.setEnabled(false);
        cboTrangThai.setEnabled(false);
        txtMaNguoiDung.setEnabled(false);
        txtMaNguoiDung.setText(NguoiDungController.ndOn.getMaND());
        loadTablePhieuXuat(PhieuXuatController.listPhieuXuat(""));
        loadComboBoxMaCH(CuaHangController.listCuaHang(""));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        checkNgayTao = new javax.swing.JCheckBox();
        checkNgayXuat = new javax.swing.JCheckBox();
        checkTrangThai = new javax.swing.JCheckBox();
        checkNguoiLap = new javax.swing.JCheckBox();
        checkMaCH = new javax.swing.JCheckBox();
        checkMaPX = new javax.swing.JCheckBox();
        lblPhieuXuat = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPhieuXuat = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        txtMaPhieuXuat = new QLKHView.swing.TextField();
        txtNgayTao = new QLKHView.swing.TextField();
        cboMaCH = new QLKHView.swing.Combobox();
        lblMaNhaCungCap = new javax.swing.JLabel();
        txtMaNguoiDung = new QLKHView.swing.TextField();
        txtNgayXuat = new QLKHView.swing.TextField();
        cboTrangThai = new QLKHView.swing.Combobox();
        lblTrangThai1 = new javax.swing.JLabel();
        btnQuayLai1 = new QLKHView.swing.Button();
        btnThem = new QLKHView.swing.Button();
        btnTim = new QLKHView.swing.Button();
        btnSua = new QLKHView.swing.Button();
        btnXoa = new QLKHView.swing.Button();
        btnLamMoi = new QLKHView.swing.Button();
        btnXemChiTiet = new QLKHView.swing.Button();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkNgayTao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkNgayTaoMouseReleased(evt);
            }
        });
        jPanel1.add(checkNgayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 274, -1, -1));

        checkNgayXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkNgayXuatMouseReleased(evt);
            }
        });
        checkNgayXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNgayXuatActionPerformed(evt);
            }
        });
        jPanel1.add(checkNgayXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1012, 270, -1, -1));

        checkTrangThai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkTrangThaiMouseReleased(evt);
            }
        });
        jPanel1.add(checkTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1011, 360, -1, -1));

        checkNguoiLap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkNguoiLapMouseReleased(evt);
            }
        });
        jPanel1.add(checkNguoiLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(1011, 188, -1, -1));

        checkMaCH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkMaCHMouseReleased(evt);
            }
        });
        jPanel1.add(checkMaCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 366, -1, -1));

        checkMaPX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkMaPXMouseReleased(evt);
            }
        });
        jPanel1.add(checkMaPX, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 186, -1, -1));

        lblPhieuXuat.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPhieuXuat.setText("QUẢN LÝ PHIẾU XUẤT");
        jPanel1.add(lblPhieuXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        tbPhieuXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu xuất", "Ngày tạo", "Mã cửa hàng", "Người tạo", "Trạng thái", "Ngày xuất"
            }
        ));
        tbPhieuXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPhieuXuatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbPhieuXuat);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 495, 1196, 190));

        txtMaPhieuXuat.setLabelText("Mã phiếu xuất");
        jPanel1.add(txtMaPhieuXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 162, 220, -1));

        txtNgayTao.setLabelText("Ngày tạo");
        jPanel1.add(txtNgayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 253, 220, -1));

        cboMaCH.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*" }));
        cboMaCH.setLabeText("");
        jPanel1.add(cboMaCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 352, 220, -1));

        lblMaNhaCungCap.setForeground(new java.awt.Color(102, 102, 102));
        lblMaNhaCungCap.setText("Mã cửa hàng");
        jPanel1.add(lblMaNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 324, -1, 22));

        txtMaNguoiDung.setLabelText("Mã người lập phiếu");
        jPanel1.add(txtMaNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 162, 220, -1));

        txtNgayXuat.setLabelText("Ngày xuất");
        jPanel1.add(txtNgayXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 253, 221, -1));

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chua xuat", "Da xuat" }));
        cboTrangThai.setLabeText("");
        jPanel1.add(cboTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 346, 220, -1));

        lblTrangThai1.setForeground(new java.awt.Color(102, 102, 102));
        lblTrangThai1.setText("Trạng thái");
        jPanel1.add(lblTrangThai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 324, -1, -1));

        btnQuayLai1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/return.png"))); // NOI18N
        btnQuayLai1.setText("Quay lại");
        btnQuayLai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLai1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuayLai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 70, 80, -1));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 80, -1));

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/find.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        jPanel1.add(btnTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 80, -1));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 80, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 80, -1));

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        jPanel1.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 80, -1));

        btnXemChiTiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/detail.png"))); // NOI18N
        btnXemChiTiet.setText("Xem chi tiết");
        btnXemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemChiTietActionPerformed(evt);
            }
        });
        jPanel1.add(btnXemChiTiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, 100, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLKHView/image/milad-fakurian-wxvYVpjWxg4-unsplash.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemChiTietActionPerformed
        // TODO add your handling code here:
        new PhieuXuatController(this).QLPhieuXuat_ChiTietPage(txtMaPhieuXuat.getText());
    }//GEN-LAST:event_btnXemChiTietActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        txtMaPhieuXuat.setEnabled(true);
        cboMaCH.setEnabled(true);
        check = false;
        txtMaPhieuXuat.setText("");
        txtMaNguoiDung.setText(NguoiDungController.ndOn.getMaND());
        cboMaCH.setSelectedIndex(0);
        txtNgayTao.setText("");
        txtNgayXuat.setText("");
        cboTrangThai.setSelectedIndex(0);
        tb.getDataVector().removeAllElements();
        loadTablePhieuXuat(PhieuXuatController.listPhieuXuat(""));
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        new PhieuXuatController(this).doDeletePhieuXuat();
        btnLamMoiActionPerformed(evt);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        new PhieuXuatController(this).doUpdatePhieuXuat();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        new PhieuXuatController(this).doSearchPhieuXuat();
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        new PhieuXuatController(this).doAddPhieuXuat();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnQuayLai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLai1ActionPerformed
        // TODO add your handling code here:
        QLPhieuXuatForm.check = false;
        this.dispose();
        if(temp != null){
            temp.setVisible(true);
            temp = null;
        }
        else indexFormNVTN.runIndexNVTN();
    }//GEN-LAST:event_btnQuayLai1ActionPerformed

    private void tbPhieuXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPhieuXuatMouseClicked
        // TODO add your handling code here:
        boolean checkClick = tbPhieuXuat.isEditing();
        if (checkClick == false){
            JTable target = (JTable) evt.getSource();
            int rowIndex = target.getSelectedRow();
            if("Da xuat".equals((String)tbPhieuXuat.getValueAt(rowIndex,4))) {
                txtMaPhieuXuat.setEnabled(false);
                cboMaCH.setEnabled(false);
                cboTrangThai.setEnabled(false);
            } else {
                cboTrangThai.setEnabled(true);
                cboMaCH.setEnabled(true);
                txtMaPhieuXuat.setEnabled(false);
            }
            check = true;
            txtMaPhieuXuat.setText((String)tbPhieuXuat.getValueAt(rowIndex,0));
            txtNgayTao.setText((String)tbPhieuXuat.getValueAt(rowIndex,1));
            cboMaCH.setSelectedItem((String)tbPhieuXuat.getValueAt(rowIndex,2));
            txtMaNguoiDung.setText((String)tbPhieuXuat.getValueAt(rowIndex,3));
            cboTrangThai.setSelectedItem((String)tbPhieuXuat.getValueAt(rowIndex,4));
            txtNgayXuat.setText((String)tbPhieuXuat.getValueAt(rowIndex,5));
        }
    }//GEN-LAST:event_tbPhieuXuatMouseClicked

    private void checkMaPXMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMaPXMouseReleased
        // TODO add your handling code here:
        if(checkMaPX.isSelected()){
            btnThem.setEnabled(false);
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
        } else if(!checkNgayXuat.isSelected() && !checkMaCH.isSelected() && !checkMaPX.isSelected() && !checkNgayTao.isSelected() && !checkNguoiLap.isSelected() && !checkTrangThai.isSelected()){
            checkMaCH.setEnabled(true);
            checkTrangThai.setEnabled(true);
            checkNgayTao.setEnabled(true);
            checkNgayXuat.setEnabled(true);
            checkNguoiLap.setEnabled(true);
            btnThem.setEnabled(true);
            btnSua.setEnabled(true);
            btnXoa.setEnabled(true);
        }
    }//GEN-LAST:event_checkMaPXMouseReleased

    private void checkMaCHMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMaCHMouseReleased
        // TODO add your handling code here:
        if(checkMaCH.isSelected()){
            btnThem.setEnabled(false);
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
        } else if(!checkNgayXuat.isSelected() && !checkMaCH.isSelected() && !checkMaPX.isSelected() && !checkNgayTao.isSelected() && !checkNguoiLap.isSelected() && !checkTrangThai.isSelected()){
            checkNguoiLap.setEnabled(true);
            checkMaPX.setEnabled(true);
            checkNgayTao.setEnabled(true);
            checkNgayXuat.setEnabled(true);
            checkTrangThai.setEnabled(true);
            btnThem.setEnabled(true);
            btnSua.setEnabled(true);
            btnXoa.setEnabled(true);
        }
    }//GEN-LAST:event_checkMaCHMouseReleased

    private void checkNguoiLapMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkNguoiLapMouseReleased
        // TODO add your handling code here:
        if(checkNguoiLap.isSelected()){
            txtMaNguoiDung.setEnabled(true);
            btnThem.setEnabled(false);
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
        } else {
            txtMaNguoiDung.setEnabled(false);
            if(!checkNgayXuat.isSelected() && !checkMaCH.isSelected() && !checkMaPX.isSelected() && !checkNgayTao.isSelected() && !checkTrangThai.isSelected()){
                checkMaCH.setEnabled(true);
                checkMaPX.setEnabled(true);
                checkNgayTao.setEnabled(true);
                checkNgayXuat.setEnabled(true);
                checkTrangThai.setEnabled(true);
                btnThem.setEnabled(true);
                btnSua.setEnabled(true);
                btnXoa.setEnabled(true);
            }
        }
    }//GEN-LAST:event_checkNguoiLapMouseReleased

    private void checkTrangThaiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkTrangThaiMouseReleased
        // TODO add your handling code here:
        if(checkTrangThai.isSelected()){
            cboTrangThai.setEnabled(true);
            btnThem.setEnabled(false);
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
        } else {
            cboTrangThai.setEnabled(false);
            if(!checkNgayXuat.isSelected() && !checkMaCH.isSelected() && !checkMaPX.isSelected() && !checkNgayTao.isSelected() && !checkNguoiLap.isSelected()){
                checkMaCH.setEnabled(true);
                checkMaPX.setEnabled(true);
                checkNgayTao.setEnabled(true);
                checkNgayXuat.setEnabled(true);
                checkNguoiLap.setEnabled(true);
                btnThem.setEnabled(true);
                btnSua.setEnabled(true);
                btnXoa.setEnabled(true);
            }
        }
    }//GEN-LAST:event_checkTrangThaiMouseReleased

    private void checkNgayXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNgayXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkNgayXuatActionPerformed

    private void checkNgayXuatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkNgayXuatMouseReleased
        // TODO add your handling code here:
        if(checkNgayXuat.isSelected()){
            txtNgayXuat.setEnabled(true);
            btnThem.setEnabled(false);
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
        } else {
            txtNgayXuat.setEnabled(false);
            if(!checkMaCH.isSelected() && !checkMaPX.isSelected() && !checkNgayTao.isSelected() && !checkNguoiLap.isSelected() && !checkTrangThai.isSelected()){
                checkMaCH.setEnabled(true);
                checkMaPX.setEnabled(true);
                checkNguoiLap.setEnabled(true);
                checkNgayTao.setEnabled(true);
                checkTrangThai.setEnabled(true);
                btnThem.setEnabled(true);
                btnSua.setEnabled(true);
                btnXoa.setEnabled(true);
            }
        }
    }//GEN-LAST:event_checkNgayXuatMouseReleased

    private void checkNgayTaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkNgayTaoMouseReleased
        // TODO add your handling code here:
        if(checkNgayTao.isSelected()){
            txtNgayTao.setEnabled(true);
            btnThem.setEnabled(false);
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
        } else {
            txtNgayTao.setEnabled(false);
            if(!checkNgayXuat.isSelected() && !checkMaCH.isSelected() && !checkMaPX.isSelected() && !checkNguoiLap.isSelected() && !checkTrangThai.isSelected()){
                checkMaCH.setEnabled(true);
                checkMaPX.setEnabled(true);
                checkNguoiLap.setEnabled(true);
                checkNgayXuat.setEnabled(true);
                checkTrangThai.setEnabled(true);
                btnThem.setEnabled(true);
                btnSua.setEnabled(true);
                btnXoa.setEnabled(true);
            }
        }
    }//GEN-LAST:event_checkNgayTaoMouseReleased
    public static void loadTablePhieuXuat(ArrayList<PhieuXuatModel> lpx){
         tb.getDataVector().removeAllElements();
        for(int i=0; i<lpx.size(); i++){
            String[] px = {lpx.get(i).getMaPhieuXuat(), lpx.get(i).getNgayTao(), lpx.get(i).getMaCH(), lpx.get(i).getMaND(), lpx.get(i).getTrangThai(), lpx.get(i).getNgayXuat()};
            tb.addRow(px);
            tbPhieuXuat.setModel(tb);
        }
    }
    
    public static void loadComboBoxMaCH(ArrayList<CuaHangModel> lch){
        for(int i=0; i<lch.size(); i++){
            cboMaCH.addItem(lch.get(i).getMaCH());
        }
    }
        public static PhieuXuatModel getPhieuXuatInput(){
       PhieuXuatModel px = new PhieuXuatModel();
       px.setMaPhieuXuat(txtMaPhieuXuat.getText());
       px.setMaCH(cboMaCH.getSelectedItem().toString());
       px.setMaND(txtMaNguoiDung.getText());
       px.setNgayTao(txtNgayTao.getText());
       px.setTrangThai(cboTrangThai.getSelectedItem().toString());
       px.setNgayXuat(txtNgayXuat.getText());
       return px;
    }    
    public static boolean xacNhanXoa(){
        int input = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        return input == JOptionPane.YES_OPTION;
    }
    
    public void showMessage(String msg, boolean checkMsg){
        if(checkMsg){
            JOptionPane.showMessageDialog(this, msg,"Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else JOptionPane.showMessageDialog(this, msg,"Thông báo", JOptionPane.ERROR_MESSAGE);
    }
    /**
     */
    public static void runQLPhieuXuat() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLPhieuXuatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLPhieuXuatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLPhieuXuatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLPhieuXuatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(() -> {
            new QLPhieuXuatForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private QLKHView.swing.Button btnLamMoi;
    private QLKHView.swing.Button btnQuayLai1;
    private QLKHView.swing.Button btnSua;
    private QLKHView.swing.Button btnThem;
    private QLKHView.swing.Button btnTim;
    private QLKHView.swing.Button btnXemChiTiet;
    private QLKHView.swing.Button btnXoa;
    protected static QLKHView.swing.Combobox cboMaCH;
    protected static QLKHView.swing.Combobox cboTrangThai;
    public static javax.swing.JCheckBox checkMaCH;
    public static javax.swing.JCheckBox checkMaPX;
    public static javax.swing.JCheckBox checkNgayTao;
    public static javax.swing.JCheckBox checkNgayXuat;
    public static javax.swing.JCheckBox checkNguoiLap;
    public static javax.swing.JCheckBox checkTrangThai;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMaNhaCungCap;
    private javax.swing.JLabel lblPhieuXuat;
    private javax.swing.JLabel lblTrangThai1;
    protected static javax.swing.JTable tbPhieuXuat;
    protected static QLKHView.swing.TextField txtMaNguoiDung;
    protected static QLKHView.swing.TextField txtMaPhieuXuat;
    protected static QLKHView.swing.TextField txtNgayTao;
    protected static QLKHView.swing.TextField txtNgayXuat;
    // End of variables declaration//GEN-END:variables
}
