/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QLKHView;
import QLKHModel.*;
import QLKHController.*;
import static QLKHView.indexFormQL.temp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.temporal.Temporal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author VTTDung
 */
public class QLPhieuNhapForm extends javax.swing.JFrame {

    /**
     * Creates new form QLPhieuNhapForm
     */
    public static boolean check;
    final static String header[] = {"Mã phiếu nhập","Ngày tạo","Mã nhà cung cấp","Người tạo","Trạng thái","Ngày nhập","Tổng giá trị"};
    final static DefaultTableModel tb = new DefaultTableModel(header, 0);
    public QLPhieuNhapForm() {
        initComponents();
        txtNgayTao.setEnabled(false);
        txtNgayNhap.setEnabled(false);
        cboTrangThai.setEnabled(false);
        txtTongGiaTri.setEnabled(false);
        txtMaNguoiDung.setEnabled(false);
        txtMaNguoiDung.setText(NguoiDungController.ndOn.getMaND());
        loadComboBoxMaNCC(NhaCungCapController.listNhaCungCap(""));
        loadTablePhieuNhap(PhieuNhapController.listPhieuNhap(""));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        checkMaPN = new javax.swing.JCheckBox();
        checkNgayTao = new javax.swing.JCheckBox();
        checkNgayNhap = new javax.swing.JCheckBox();
        checkMaNCC = new javax.swing.JCheckBox();
        checkNguoiLap = new javax.swing.JCheckBox();
        checkTrangThai = new javax.swing.JCheckBox();
        lblPhieuNhap = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPhieuNhap = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        txtMaPhieuNhap = new QLKHView.swing.TextField();
        txtNgayTao = new QLKHView.swing.TextField();
        txtNgayNhap = new QLKHView.swing.TextField();
        txtTongGiaTri = new QLKHView.swing.TextField();
        txtMaNguoiDung = new QLKHView.swing.TextField();
        cboMaNCC = new QLKHView.swing.Combobox();
        cboTrangThai = new QLKHView.swing.Combobox();
        lblMaNhaCungCap = new javax.swing.JLabel();
        lblTrangThai = new javax.swing.JLabel();
        btnQuayLai = new QLKHView.swing.Button();
        btnThem = new QLKHView.swing.Button();
        btnTim = new QLKHView.swing.Button();
        btnSua = new QLKHView.swing.Button();
        btnXoa = new QLKHView.swing.Button();
        btnLamMoi = new QLKHView.swing.Button();
        btnXemChiTiet = new QLKHView.swing.Button();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkMaPN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkMaPNMouseReleased(evt);
            }
        });
        jPanel1.add(checkMaPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        checkNgayTao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkNgayTaoMouseReleased(evt);
            }
        });
        jPanel1.add(checkNgayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        checkNgayNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkNgayNhapMouseReleased(evt);
            }
        });
        jPanel1.add(checkNgayNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 220, -1, -1));

        checkMaNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkMaNCCMouseReleased(evt);
            }
        });
        jPanel1.add(checkMaNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        checkNguoiLap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkNguoiLapMouseReleased(evt);
            }
        });
        checkNguoiLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNguoiLapActionPerformed(evt);
            }
        });
        jPanel1.add(checkNguoiLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 150, -1, -1));

        checkTrangThai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                checkTrangThaiMouseReleased(evt);
            }
        });
        jPanel1.add(checkTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 310, -1, -1));

        lblPhieuNhap.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPhieuNhap.setText("QUẢN LÝ PHIẾU NHẬP");
        jPanel1.add(lblPhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 37, -1, -1));

        tbPhieuNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu nhập", "Ngày tạo", "Mã nhà cung cấp", "Người tạo", "Trạng thái", "Ngày nhập", "Tổng giá trị"
            }
        ));
        tbPhieuNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPhieuNhapMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbPhieuNhap);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 1200, 190));

        txtMaPhieuNhap.setLabelText("Mã phiếu nhập");
        jPanel1.add(txtMaPhieuNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 220, -1));

        txtNgayTao.setLabelText("Ngày tạo");
        jPanel1.add(txtNgayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 220, -1));

        txtNgayNhap.setLabelText("Ngày nhập");
        jPanel1.add(txtNgayNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 221, -1));

        txtTongGiaTri.setLabelText("Tổng giá trị");
        jPanel1.add(txtTongGiaTri, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 275, 70));

        txtMaNguoiDung.setLabelText("Mã người lập phiếu");
        jPanel1.add(txtMaNguoiDung, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 220, -1));

        cboMaNCC.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*" }));
        cboMaNCC.setLabeText("");
        jPanel1.add(cboMaNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 220, 50));

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Chua nhap", "Da nhap" }));
        cboTrangThai.setLabeText("");
        cboTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTrangThaiActionPerformed(evt);
            }
        });
        jPanel1.add(cboTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 220, 50));

        lblMaNhaCungCap.setForeground(new java.awt.Color(102, 102, 102));
        lblMaNhaCungCap.setText("Mã nhà cung cấp");
        jPanel1.add(lblMaNhaCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        lblTrangThai.setForeground(new java.awt.Color(102, 102, 102));
        lblTrangThai.setText("Trạng thái");
        jPanel1.add(lblTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, -1, -1));

        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/return.png"))); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuayLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 60, 80, -1));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 80, -1));

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/find.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        jPanel1.add(btnTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 80, -1));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 80, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clear.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 80, -1));

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        jPanel1.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, 80, -1));

        btnXemChiTiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/detail.png"))); // NOI18N
        btnXemChiTiet.setText("Xem chi tiết");
        btnXemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemChiTietActionPerformed(evt);
            }
        });
        jPanel1.add(btnXemChiTiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 370, 100, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLKHView/image/milad-fakurian-wxvYVpjWxg4-unsplash.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 1200, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemChiTietActionPerformed
        // TODO add your handling code here:
        new PhieuNhapController(this).QLPhieuNhap_ChiTietPage(txtMaPhieuNhap.getText());
    }//GEN-LAST:event_btnXemChiTietActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        txtMaPhieuNhap.setEnabled(true);
        cboMaNCC.setEnabled(true);
        check = false;
        txtMaPhieuNhap.setText("");
        txtMaNguoiDung.setText(NguoiDungController.ndOn.getMaND());
        cboMaNCC.setSelectedIndex(0);
        txtNgayTao.setText("");
        txtNgayNhap.setText("");
        txtTongGiaTri.setText("");
        cboTrangThai.setSelectedIndex(0);
        tb.getDataVector().removeAllElements();
        loadTablePhieuNhap(PhieuNhapController.listPhieuNhap(""));
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        new PhieuNhapController(this).doDeletePhieuNhap();
        btnLamMoiActionPerformed(evt);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        new PhieuNhapController(this).doUpdatePhieuNhap();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        new PhieuNhapController(this).doSearchPhieuNhap();
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        new PhieuNhapController(this).doAddPhieuNhap();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        QLPhieuNhapForm.check = false;
        this.dispose();
        if(temp != null){
            temp.setVisible(true);
            temp = null;
        }
        else indexFormNVTN.runIndexNVTN();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void tbPhieuNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPhieuNhapMouseClicked
        // TODO add your handling code here:
        boolean checkClick = tbPhieuNhap.isEditing();
        if (checkClick == false){
            JTable target = (JTable) evt.getSource();
            int rowIndex = target.getSelectedRow();
            if("Da nhap".equals((String)tbPhieuNhap.getValueAt(rowIndex,4))) {
                txtMaPhieuNhap.setEnabled(false);
                cboMaNCC.setEnabled(false);
                cboTrangThai.setEnabled(false);
            } else {
                cboTrangThai.setEnabled(true);
                cboMaNCC.setEnabled(true);
                txtMaPhieuNhap.setEnabled(false);
            }
            check = true;
            txtMaPhieuNhap.setText((String)tbPhieuNhap.getValueAt(rowIndex,0));
            txtNgayTao.setText((String)tbPhieuNhap.getValueAt(rowIndex,1));
            cboMaNCC.setSelectedItem((String)tbPhieuNhap.getValueAt(rowIndex,2));
            txtMaNguoiDung.setText((String)tbPhieuNhap.getValueAt(rowIndex,3));
            cboTrangThai.setSelectedItem((String)tbPhieuNhap.getValueAt(rowIndex,4));
            txtNgayNhap.setText((String)tbPhieuNhap.getValueAt(rowIndex,5));
            txtTongGiaTri.setText((String)tbPhieuNhap.getValueAt(rowIndex, 6));
        }
    }//GEN-LAST:event_tbPhieuNhapMouseClicked

    private void checkTrangThaiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkTrangThaiMouseReleased
        // TODO add your handling code here:
        if(checkTrangThai.isSelected()){
            cboTrangThai.setEnabled(true);
            btnThem.setEnabled(false);
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
        } else {
            cboTrangThai.setEnabled(false);
            if(!checkNgayNhap.isSelected() && !checkMaNCC.isSelected() && !checkMaPN.isSelected() && !checkNgayTao.isSelected() && !checkNguoiLap.isSelected()){
                checkMaNCC.setEnabled(true);
                checkMaPN.setEnabled(true);
                checkNgayTao.setEnabled(true);
                checkNgayNhap.setEnabled(true);
                checkNguoiLap.setEnabled(true);
                btnThem.setEnabled(true);
                btnSua.setEnabled(true);
                btnXoa.setEnabled(true);
            }
        }
    }//GEN-LAST:event_checkTrangThaiMouseReleased

    private void checkNguoiLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNguoiLapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkNguoiLapActionPerformed

    private void checkNguoiLapMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkNguoiLapMouseReleased
        // TODO add your handling code here:
        if(checkNguoiLap.isSelected()){
            txtMaNguoiDung.setEnabled(true);
            btnThem.setEnabled(false);
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
        } else {
            txtMaNguoiDung.setEnabled(false);
            if(!checkNgayNhap.isSelected() && !checkMaNCC.isSelected() && !checkMaPN.isSelected() && !checkNgayTao.isSelected() && !checkTrangThai.isSelected()){
                checkMaNCC.setEnabled(true);
                checkMaPN.setEnabled(true);
                checkNgayTao.setEnabled(true);
                checkNgayNhap.setEnabled(true);
                checkTrangThai.setEnabled(true);
                btnThem.setEnabled(true);
                btnSua.setEnabled(true);
                btnXoa.setEnabled(true);
            }
        }
    }//GEN-LAST:event_checkNguoiLapMouseReleased

    private void checkMaNCCMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMaNCCMouseReleased
        // TODO add your handling code here:
        if(checkMaNCC.isSelected()){
            btnThem.setEnabled(false);
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
        } else if(!checkNgayNhap.isSelected() && !checkMaNCC.isSelected() && !checkMaPN.isSelected() && !checkNgayTao.isSelected() && !checkNguoiLap.isSelected() && !checkTrangThai.isSelected()){
            checkNguoiLap.setEnabled(true);
            checkMaPN.setEnabled(true);
            checkNgayTao.setEnabled(true);
            checkNgayNhap.setEnabled(true);
            checkTrangThai.setEnabled(true);
            btnThem.setEnabled(true);
            btnSua.setEnabled(true);
            btnXoa.setEnabled(true);
        }

    }//GEN-LAST:event_checkMaNCCMouseReleased

    private void checkNgayNhapMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkNgayNhapMouseReleased
        // TODO add your handling code here:
        if(checkNgayNhap.isSelected()){
            txtNgayNhap.setEnabled(true);
            btnThem.setEnabled(false);
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
        } else {
            txtNgayNhap.setEnabled(false);
            if(!checkMaNCC.isSelected() && !checkMaPN.isSelected() && !checkNgayTao.isSelected() && !checkNguoiLap.isSelected() && !checkTrangThai.isSelected()){
                checkMaNCC.setEnabled(true);
                checkMaPN.setEnabled(true);
                checkNguoiLap.setEnabled(true);
                checkNgayTao.setEnabled(true);
                checkTrangThai.setEnabled(true);
                btnThem.setEnabled(true);
                btnSua.setEnabled(true);
                btnXoa.setEnabled(true);
            }
        }
    }//GEN-LAST:event_checkNgayNhapMouseReleased

    private void checkNgayTaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkNgayTaoMouseReleased
        // TODO add your handling code here:
        if(checkNgayTao.isSelected()){
            txtNgayTao.setEnabled(true);
            btnThem.setEnabled(false);
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
        } else {
            txtNgayTao.setEnabled(false);
            if(!checkNgayNhap.isSelected() && !checkMaNCC.isSelected() && !checkMaPN.isSelected() && !checkNguoiLap.isSelected() && !checkTrangThai.isSelected()){
                checkMaNCC.setEnabled(true);
                checkMaPN.setEnabled(true);
                checkNguoiLap.setEnabled(true);
                checkNgayNhap.setEnabled(true);
                checkTrangThai.setEnabled(true);
                btnThem.setEnabled(true);
                btnSua.setEnabled(true);
                btnXoa.setEnabled(true);
            }
        }
    }//GEN-LAST:event_checkNgayTaoMouseReleased

    private void checkMaPNMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMaPNMouseReleased
        // TODO add your handling code here:
        if(checkMaPN.isSelected()){
            btnThem.setEnabled(false);
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
        } else if(!checkNgayNhap.isSelected() && !checkMaNCC.isSelected() && !checkMaPN.isSelected() && !checkNgayTao.isSelected() && !checkNguoiLap.isSelected() && !checkTrangThai.isSelected()){
            checkMaNCC.setEnabled(true);
            checkTrangThai.setEnabled(true);
            checkNgayTao.setEnabled(true);
            checkNgayNhap.setEnabled(true);
            checkNguoiLap.setEnabled(true);
            btnThem.setEnabled(true);
            btnSua.setEnabled(true);
            btnXoa.setEnabled(true);
        }
    }//GEN-LAST:event_checkMaPNMouseReleased

    private void cboTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTrangThaiActionPerformed

    @SuppressWarnings("unchecked")
    public static void loadComboBoxMaNCC(ArrayList<NhaCungCapModel> lcc){
        for(int i=0; i<lcc.size(); i++){
            cboMaNCC.addItem(lcc.get(i).getMaNCC());
        }
    }    public static void loadTablePhieuNhap(ArrayList<PhieuNhapModel> lpn){
         tb.getDataVector().removeAllElements();
        for(int i=0; i<lpn.size(); i++){
            String[] pn = {lpn.get(i).getMaPhieuNhap(), lpn.get(i).getNgayTao(), lpn.get(i).getMaNCC(), lpn.get(i).getMaND(), lpn.get(i).getTrangThai(), lpn.get(i).getNgayNhap(),String.valueOf(lpn.get(i).getTongTien())};
            tb.addRow(pn);
            tbPhieuNhap.setModel(tb);
        }
    }
    public static PhieuNhapModel getPhieuNhapInput(){
       PhieuNhapModel pn = new PhieuNhapModel();
       pn.setMaPhieuNhap(txtMaPhieuNhap.getText());
       pn.setMaNCC(cboMaNCC.getSelectedItem().toString());
       pn.setMaND(txtMaNguoiDung.getText());
       pn.setNgayTao(txtNgayTao.getText());
       pn.setTrangThai(cboTrangThai.getSelectedItem().toString());
       pn.setNgayNhap(txtNgayNhap.getText());
       return pn;
    }    public static boolean xacNhanXoa(){
        int input = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không?","Thông báo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        return input == JOptionPane.YES_OPTION;
    }
    
    public void showMessage(String msg, boolean checkMsg){
        if(checkMsg){
            JOptionPane.showMessageDialog(this, msg,"Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else JOptionPane.showMessageDialog(this, msg,"Thông báo", JOptionPane.ERROR_MESSAGE);
    }
    /**
     */
   public static void runQLPhieuNhap() {
        /* Create and display the form */
         java.awt.EventQueue.invokeLater(() -> {
            new QLPhieuNhapForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private QLKHView.swing.Button btnLamMoi;
    private QLKHView.swing.Button btnQuayLai;
    private QLKHView.swing.Button btnSua;
    private QLKHView.swing.Button btnThem;
    private QLKHView.swing.Button btnTim;
    private QLKHView.swing.Button btnXemChiTiet;
    private QLKHView.swing.Button btnXoa;
    protected static QLKHView.swing.Combobox cboMaNCC;
    protected static QLKHView.swing.Combobox cboTrangThai;
    public static javax.swing.JCheckBox checkMaNCC;
    public static javax.swing.JCheckBox checkMaPN;
    public static javax.swing.JCheckBox checkNgayNhap;
    public static javax.swing.JCheckBox checkNgayTao;
    public static javax.swing.JCheckBox checkNguoiLap;
    public static javax.swing.JCheckBox checkTrangThai;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMaNhaCungCap;
    private javax.swing.JLabel lblPhieuNhap;
    private javax.swing.JLabel lblTrangThai;
    protected static javax.swing.JTable tbPhieuNhap;
    protected static QLKHView.swing.TextField txtMaNguoiDung;
    protected static QLKHView.swing.TextField txtMaPhieuNhap;
    protected static QLKHView.swing.TextField txtNgayNhap;
    protected static QLKHView.swing.TextField txtNgayTao;
    protected static QLKHView.swing.TextField txtTongGiaTri;
    // End of variables declaration//GEN-END:variables
}
